version: '3.8'

services:
  server:
    build: ./server
    container_name: chat-server
    hostname: chat-server
    networks:
      - chat-network
    volumes:
      - ./server:/app:cached
    ports:
      - "9999:9999"
    stdin_open: true
    tty: true

  client:
    build: ./client
    container_name: chat-client
    hostname: chat-client
    networks:
      - chat-network
    volumes:
      - ./client:/app:cached
    stdin_open: true
    tty: true

networks:
  chat-network:
    driver: bridge